#!/usr/bin/env bash
# Lifecycle of the stack the Playwright acceptance suite drives.
#
# This is the ONLY place the E2E stack is started, stopped or perturbed — the
# Makefile target, Playwright's global setup, and the two tests that have to
# damage the store on purpose (§13-4 delete kairos.db, §13-5 rm -rf objects/<id>)
# all call these subcommands. One implementation means a developer who runs
# `stack.sh up` by hand gets byte-identical conditions to `make test-e2e`.
#
#   ./e2e/scripts/stack.sh up             # fresh data dir + stack + replay, waits ready
#   ./e2e/scripts/stack.sh down           # stop replay, remove the stack
#   ./e2e/scripts/stack.sh wait           # readiness only (no side effects)
#   ./e2e/scripts/stack.sh stop|start     # keep the containers, cycle them
#   ./e2e/scripts/stack.sh start-lenient  # boot without requiring a readable catalog
#   ./e2e/scripts/stack.sh rm-db          # §13-4: delete the index
#   ./e2e/scripts/stack.sh rm-objects ID  # §13-5: out-of-band rm -rf
#   ./e2e/scripts/stack.sh ps|logs|env
#
# The stack runs on its own ports, its own ROS domain and its own data dir
# (e2e/stack.env), so it can sit beside a developer's `make up` stack.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$HERE"

ENV_FILE="e2e/stack.env"
RUN_DIR="e2e/.run"
SERVICE_ENV="$RUN_DIR/service.env"
HOST_ENV="$RUN_DIR/host.env"
PROJECT="kairos-e2e"
REPLAY_PROJECT="kairos-e2e-replay"
TEST_COMPOSE="deploy/test/compose.yaml"
REPLAY_CID_FILE="$RUN_DIR/replay.cid"

# The services the acceptance suite drives. The webrtc streamer and the topic
# probe are deliberately absent: no scenario asserts on a camera preview, and
# two 1 GB ROS images that nothing reads would only slow the gate down.
SERVICES="recorder monitor orchestrator dora_runner frontend"

# Same derivation as the Makefile, so `make build` and this script tag and find
# the same images instead of one silently building :dev and the other looking
# for :0.1.0.
KAIROS_VERSION="$(cat VERSION 2>/dev/null || echo dev)"
export KAIROS_VERSION

# Export the whole profile. `docker compose --env-file` alone is not enough:
# compose lets the shell environment win over an env file, so a `ROBOT=<robot>`
# exported by the Makefile (or left in a developer's shell) would otherwise
# select the wrong recording config for the acceptance stack.
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

# compose runs the orchestrator/dora_runner as ${UID}:${GID} so the host-owned
# data mount stays writable. bash makes UID readonly, so it cannot simply be
# exported — it is written to a generated env file compose reads instead.
mkdir -p "$RUN_DIR"
printf 'UID=%s\nGID=%s\n' "$(id -u)" "$(id -g)" > "$HOST_ENV"

DATA_ABS="$HERE/${DATA_DIR#./}"
ORCH="http://127.0.0.1:${API_ORCH_PORT}"
REC="http://127.0.0.1:${RECORDER_PORT}"
DORA="http://127.0.0.1:${DORA_RUNNER_PORT}"
FE="http://127.0.0.1:${FRONTEND_PORT}"
MON="http://127.0.0.1:${TOPIC_MONITOR_PORT}"

compose() {
  docker compose --env-file "$ENV_FILE" --env-file "$HOST_ENV" \
    -f compose.yaml -p "$PROJECT" "$@"
}
say() { printf '\033[36me2e:\033[0m %s\n' "$*"; }
die() { printf '\033[31me2e: %s\033[0m\n' "$*" >&2; exit 1; }

# ---- image guard ------------------------------------------------------------
# Follows the repo rule that `up` never builds (deploy/test and the Makefile do
# the same): building needs a network even when nothing changed. The failure
# has to name the fix, not just the missing tag.
require_images() {
  local missing=()
  for img in \
    "kairos-rosbag2-recorder:${ROS_DISTRO}" \
    "kairos-topic-monitor:${ROS_DISTRO}" \
    "kairos-api-orchestrator:${KAIROS_VERSION}" \
    "kairos-dora-runner:${KAIROS_VERSION}" \
    "kairos-frontend:${KAIROS_VERSION}"
  do
    docker image inspect "$img" >/dev/null 2>&1 || missing+=("$img")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    printf '\033[31me2e: missing images: %s\033[0m\n' "${missing[*]}" >&2
    printf 'Build them first (this needs a network):\n  make build\n' >&2
    printf 'A stale image is worse than a missing one — rebuild after changing services/.\n' >&2
    exit 1
  fi
  docker image inspect "kairos-rosbag-player:${ROS_DISTRO}" >/dev/null 2>&1 || {
    say "building the replay harness image (kairos-rosbag-player:${ROS_DISTRO})"
    docker compose --env-file "$ENV_FILE" -f "$TEST_COMPOSE" build rosbag_player
  }
}

# ---- generated container env ------------------------------------------------
# DATA_DIR is the one key whose host and container meaning differ: the compose
# volume needs the host path, the services need /data. Generating the container
# copy (instead of maintaining a second file) removes the only way the two env
# files could drift apart.
write_service_env() {
  mkdir -p "$RUN_DIR"
  {
    echo "# GENERATED by e2e/scripts/stack.sh from $ENV_FILE — do not edit."
    grep -vE '^\s*(DATA_DIR|KAIROS_ENV_FILE)\s*=' "$ENV_FILE"
    echo "DATA_DIR=/data"
  } > "$SERVICE_ENV"
}

# ---- readiness --------------------------------------------------------------
http_ok() { curl -fsS --max-time 3 -o /dev/null "$1" 2>/dev/null; }

wait_for() {
  local name="$1" url="$2" deadline=$(( SECONDS + ${3:-90} ))
  while [ "$SECONDS" -lt "$deadline" ]; do
    if http_ok "$url"; then say "ready: $name"; return 0; fi
    sleep 1
  done
  printf '\033[31me2e: %s never became ready at %s\033[0m\n' "$name" "$url" >&2
  compose logs --tail=40 "${4:-}" 2>/dev/null || true
  return 1
}

cmd_wait() {
  wait_for orchestrator "$ORCH/healthz" 90 orchestrator || die "orchestrator not ready"
  # /healthz is liveness by design (see compose.yaml) — it answers before the
  # store is usable. The catalog answering is what the tests actually need, and
  # waiting on it here turns a startup race into a readiness wait instead of a
  # 500 in the middle of the first scenario.
  #
  # WAIT_CATALOG=0 is for the one scenario that is TESTING whether the catalog
  # survives a rebuild: there, an unreadable catalog is the finding, and it has
  # to be reported by the assertion that explains it rather than by a readiness
  # timeout here.
  if [ "${WAIT_CATALOG:-1}" = "1" ]; then
    wait_for catalog "$ORCH/api/v1/captures?limit=1" 90 orchestrator || die "catalog not readable"
  fi
  wait_for recorder     "$REC/healthz"  90 recorder     || die "recorder not ready"
  wait_for dora_runner  "$DORA/healthz" 120 dora_runner || die "dora_runner not ready"
  wait_for frontend     "$FE/"          60 frontend     || die "frontend not ready"
  # The monitor is not on any scenario's critical path (Collect reads its topic
  # list from GET /config, not from the monitor), so a slow DDS discovery must
  # not fail the gate — but staying silent about it would hide a real outage.
  if wait_for monitor "$MON/readyz" 45 monitor; then :; else
    say "WARNING: topic_monitor is not ready — live Hz panels will be empty"
  fi
}

# ---- subcommands ------------------------------------------------------------
cmd_reset() {
  say "resetting $DATA_ABS"
  # The recorder runs as root and its objects/<id>/ trees are root-owned, so the
  # host user cannot always remove them. Do it from a container that can.
  if [ -d "$DATA_ABS" ]; then
    docker run --rm --user 0:0 -v "$DATA_ABS:/data" \
      --entrypoint sh "kairos-api-orchestrator:${KAIROS_VERSION}" \
      -c 'rm -rf /data/..?* /data/.[!.]* /data/*' >/dev/null 2>&1 || true
  fi
  rm -rf "$DATA_ABS"
  mkdir -p "$DATA_ABS"
  write_service_env
}

cmd_up() {
  require_images
  # Remove any previous containers BEFORE wiping the data dir. `up -d` reuses a
  # running container, and a service that keeps running while its data
  # directory is deleted underneath it holds an open handle to a file that no
  # longer exists — the orchestrator then answers /healthz (liveness) perfectly
  # while every catalog read 500s. Costing a few seconds of recreation is the
  # price of each run starting from an actually-fresh process.
  cmd_down
  cmd_reset
  say "starting stack ($PROJECT) on ports ${API_ORCH_PORT}/${FRONTEND_PORT}, ROS_DOMAIN_ID=$ROS_DOMAIN_ID"
  compose up -d $SERVICES
  cmd_wait
  cmd_replay_start
  say "up — UI at $FE/  API at $ORCH/api/v1"
}

cmd_down() {
  cmd_replay_stop
  say "removing stack ($PROJECT)"
  compose down --remove-orphans >/dev/null 2>&1 || true
}

# `stop`/`start` keep the containers (and therefore the exact same env) so the
# §13-4 rebuild scenario restarts the SAME stack rather than a new one that
# might differ in some way the test would then be crediting to the rebuild.
cmd_stop()  { say "stopping containers"; compose stop >/dev/null; }
cmd_start() { say "starting containers"; compose start >/dev/null; cmd_wait; }
# Boot without insisting the catalog answers — see WAIT_CATALOG in cmd_wait.
cmd_start_lenient() {
  say "starting containers (catalog readiness not required)"
  compose start >/dev/null
  WAIT_CATALOG=0 cmd_wait
}

cmd_replay_start() {
  cmd_replay_stop
  local bag="${BAG:-airoa-moma-mcap/235210}"
  say "replaying $bag on ROS_DOMAIN_ID=$ROS_DOMAIN_ID (loop)"
  mkdir -p "$RUN_DIR"
  BAG="$bag" LOOP=--loop \
    docker compose --env-file "$ENV_FILE" -f "$TEST_COMPOSE" -p "$REPLAY_PROJECT" \
      run --rm -d rosbag_player > "$REPLAY_CID_FILE"
  say "replay container $(cut -c1-12 < "$REPLAY_CID_FILE")"
}

cmd_replay_stop() {
  if [ -f "$REPLAY_CID_FILE" ]; then
    docker rm -f "$(cat "$REPLAY_CID_FILE")" >/dev/null 2>&1 || true
    rm -f "$REPLAY_CID_FILE"
  fi
  docker compose --env-file "$ENV_FILE" -f "$TEST_COMPOSE" -p "$REPLAY_PROJECT" \
    down --remove-orphans >/dev/null 2>&1 || true
}

# §13-4: delete the index and nothing else. The sidecars stay, which is the
# whole point — the catalog has to come back from them.
cmd_rm_db() {
  say "deleting $DATA_ABS/kairos.db"
  rm -f "$DATA_ABS/kairos.db" "$DATA_ABS/kairos.db-wal" "$DATA_ABS/kairos.db-shm"
  [ ! -e "$DATA_ABS/kairos.db" ] || die "kairos.db still present"
}

# §13-5: the out-of-band removal kairos must never mistake for a deletion.
# Root-owned tree (the recorder wrote it), so this goes through a container.
cmd_rm_objects() {
  local id="${1:?capture_id required}"
  [ -d "$DATA_ABS/objects/$id" ] || die "objects/$id does not exist — nothing to remove"
  say "rm -rf objects/$id (out of band)"
  docker run --rm --user 0:0 -v "$DATA_ABS:/data" \
    --entrypoint sh "kairos-api-orchestrator:${KAIROS_VERSION}" \
    -c "rm -rf '/data/objects/$id'"
  [ ! -e "$DATA_ABS/objects/$id" ] || die "objects/$id survived the removal"
}

cmd_env() {
  # Consumed by the Playwright fixtures, so they never re-parse stack.env.
  cat <<EOF
E2E_BASE_URL=$FE
E2E_API_URL=$ORCH/api/v1
E2E_ORCH_URL=$ORCH
E2E_DATA_DIR=$DATA_ABS
E2E_PROJECT=$PROJECT
E2E_STACK_SH=$HERE/e2e/scripts/stack.sh
EOF
}

case "${1:-}" in
  up)           cmd_up ;;
  down)         cmd_down ;;
  reset)        cmd_reset ;;
  wait)         cmd_wait ;;
  stop)          cmd_stop ;;
  start)         cmd_start ;;
  start-lenient) cmd_start_lenient ;;
  replay-start) cmd_replay_start ;;
  replay-stop)  cmd_replay_stop ;;
  rm-db)        cmd_rm_db ;;
  rm-objects)   shift; cmd_rm_objects "$@" ;;
  env)          cmd_env ;;
  ps)           compose ps ;;
  logs)         shift; compose logs --tail="${TAIL:-100}" "$@" ;;
  *)
    grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'
    exit 1 ;;
esac
